use crate::road::components::{RoadSegmentType, Track};
use bevy::prelude::*;

const TRACK_1_LAYOUT: [RoadSegmentType; 22] = [
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::CornerRight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::CornerRight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::CornerRight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::CornerRight,
];

const TRACK_2_LAYOUT: [RoadSegmentType; 22] = [
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::CornerLeft,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::CornerLeft,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::CornerLeft,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::CornerLeft,
];

const TRACK_3_LAYOUT: [RoadSegmentType; 175 - 54] = [
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::CornerLeft,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::CornerRight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::CornerLeft,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::CornerLeft,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::CornerRight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::CornerLeft,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::CornerLeft,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::CornerLeft,
    RoadSegmentType::CornerRight,
    RoadSegmentType::CornerLeft,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::CornerLeft,
    RoadSegmentType::CornerLeft,
    RoadSegmentType::CornerRight,
    RoadSegmentType::CornerLeft,
    RoadSegmentType::CornerRight,
    RoadSegmentType::CornerLeft,
    RoadSegmentType::CornerRight,
    RoadSegmentType::CornerLeft,
    RoadSegmentType::CornerRight,
    RoadSegmentType::CornerLeft,
    RoadSegmentType::CornerRight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::CornerRight,
    RoadSegmentType::CornerLeft,
    RoadSegmentType::CornerRight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
];

pub const TRACK_1: Track = Track {
    layout: &TRACK_1_LAYOUT,
    starting_point: Vec2::new(0.0, 0.0),
};

pub const TRACK_2: Track = Track {
    layout: &TRACK_2_LAYOUT,
    starting_point: Vec2::new(-100.0, 0.0),
};

pub const TRACK_3: Track = Track {
    layout: &TRACK_3_LAYOUT,
    starting_point: Vec2::new(-100.0, 0.0),
};
