use crate::road::components::{RoadSegmentType, Track};
use crate::road::constants::*;
use bevy::prelude::*;

const TRACK_1_LAYOUT: [RoadSegmentType; 41-5] = [
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::CornerRight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::CornerRight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::CornerRight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::CornerRight,
];


const TRACK_2_LAYOUT: [RoadSegmentType; 84-50] = [
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::CornerLeft,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::CornerRight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::CornerRight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::CornerRight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::CornerRight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::CornerRight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
];


const TRACK_3_LAYOUT: [RoadSegmentType; 147 - 83] = [
    RoadSegmentType::Straight,
    RoadSegmentType::CornerLeft,
    RoadSegmentType::Straight,
    RoadSegmentType::CornerRight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::CornerLeft,
    RoadSegmentType::Straight,
    RoadSegmentType::CornerLeft,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::CornerRight,
    RoadSegmentType::Straight,
    RoadSegmentType::CornerLeft,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::CornerLeft,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::CornerLeft,
    RoadSegmentType::CornerRight,
    RoadSegmentType::CornerLeft,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::CornerLeft,
    RoadSegmentType::CornerLeft,
    RoadSegmentType::CornerRight,
    RoadSegmentType::CornerLeft,
    RoadSegmentType::CornerRight,
    RoadSegmentType::CornerLeft,
    RoadSegmentType::CornerRight,
    RoadSegmentType::CornerLeft,
    RoadSegmentType::CornerRight,
    RoadSegmentType::CornerLeft,
    RoadSegmentType::CornerRight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::CornerRight,
    RoadSegmentType::CornerLeft,
    RoadSegmentType::CornerRight,
    RoadSegmentType::Straight,
];

// Shift starting points in units of ROAD_SEGMENT_LENGTH to enforce square fixed-size segments of screen
pub const TRACK_1: Track = Track {
    layout: &TRACK_1_LAYOUT,
    starting_point: Vec2::new(-5.0 * ROAD_SEGMENT_LENGTH, -3.0 * ROAD_SEGMENT_LENGTH),
};

pub const TRACK_2: Track = Track {
    layout: &TRACK_2_LAYOUT,
    starting_point: Vec2::new(-1.0 * ROAD_SEGMENT_LENGTH, -2.0 * ROAD_SEGMENT_LENGTH),
};

pub const TRACK_3: Track = Track {
    layout: &TRACK_3_LAYOUT,
    starting_point: Vec2::new(-2.0 * ROAD_SEGMENT_LENGTH, 0.0),
};
