use crate::road::components::{RoadSegmentType, Track};
use crate::road::constants::*;
use bevy::prelude::*;

const TRACK_1_LAYOUT: [RoadSegmentType; 41-5] = [
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::CornerRight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::CornerRight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::CornerRight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::CornerRight,
];


const TRACK_2_LAYOUT: [RoadSegmentType; 84-50] = [
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::CornerLeft,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::CornerRight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::CornerRight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::CornerRight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::CornerRight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::CornerRight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
];


const TRACK_3_LAYOUT: [RoadSegmentType; 147 - 83] = [
    RoadSegmentType::Straight,
    RoadSegmentType::CornerLeft,
    RoadSegmentType::Straight,
    RoadSegmentType::CornerRight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::CornerLeft,
    RoadSegmentType::Straight,
    RoadSegmentType::CornerLeft,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::CornerRight,
    RoadSegmentType::Straight,
    RoadSegmentType::CornerLeft,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::CornerLeft,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::CornerLeft,
    RoadSegmentType::CornerRight,
    RoadSegmentType::CornerLeft,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::CornerLeft,
    RoadSegmentType::CornerLeft,
    RoadSegmentType::CornerRight,
    RoadSegmentType::CornerLeft,
    RoadSegmentType::CornerRight,
    RoadSegmentType::CornerLeft,
    RoadSegmentType::CornerRight,
    RoadSegmentType::CornerLeft,
    RoadSegmentType::CornerRight,
    RoadSegmentType::CornerLeft,
    RoadSegmentType::CornerRight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::Straight,
    RoadSegmentType::CornerRight,
    RoadSegmentType::CornerLeft,
    RoadSegmentType::CornerRight,
    RoadSegmentType::Straight,
];

// Shift starting points in units of ROAD_SEGMENT_LENGTH to enforce square fixed-size segments of screen

/// Returns the track for the given level number (1, 2, or 3)
pub fn get_track(level: usize) -> Track {
    match level {
        1 => Track {
            layout: TRACK_1_LAYOUT.to_vec(),
            starting_point: Vec2::new(-5.0 * ROAD_SEGMENT_LENGTH, -3.0 * ROAD_SEGMENT_LENGTH),
            prop_indices: vec![10, 25],
        },
        2 => Track {
            layout: TRACK_2_LAYOUT.to_vec(),
            starting_point: Vec2::new(-1.0 * ROAD_SEGMENT_LENGTH, -2.0 * ROAD_SEGMENT_LENGTH),
            prop_indices: vec![20, 50],
        },
        3 => Track {
            layout: TRACK_3_LAYOUT.to_vec(),
            starting_point: Vec2::new(-2.0 * ROAD_SEGMENT_LENGTH, 0.0),
            prop_indices: vec![15, 40, 70],
        },
        _ => panic!("Invalid level: {}. Only levels 1-3 are available.", level),
    }
}
